name: check
# ワークフロー実行タイミングは
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip install poetry
      - run: poetry install
      - run: poetry run black . --check
      - run: poetry run pflake8
      - run: poetry run python -m py_compile main.py
